name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/tests
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # or any version you are using

      - name: Install dependencies using lock file
        run: npm ci  # For npm, it installs dependencies using package-lock.json

      - name: Run tests
        run: npm test
